module.exports = {
    'extends': ['stylelint-config-standard-scss'],
    'plugins': [
        '@stylistic/stylelint-plugin',
        'stylelint-order',
        'stylelint-scss',
    ],
    'ignoreFiles': [
        'assets/css/*.css',
        'public/build/**',
    ],
    'rules': {
        '@stylistic/color-hex-case': 'upper',
        '@stylistic/at-rule-semicolon-space-before': 'never',
        '@stylistic/at-rule-name-space-after': 'always',
        '@stylistic/block-closing-brace-newline-after': [
            'always',
            {
                'ignoreAtRules': [
                    'if',
                    'else',
                    'elseif',
                ],
            },
        ],
        '@stylistic/declaration-colon-newline-after': 'always-multi-line',
        '@stylistic/function-comma-newline-before': 'never-multi-line',
        '@stylistic/max-line-length': 160,
        '@stylistic/media-query-list-comma-newline-before': 'never-multi-line',
        '@stylistic/selector-list-comma-newline-before': 'never-multi-line',
        '@stylistic/selector-list-comma-space-after': 'always-single-line',
        '@stylistic/string-quotes': 'single',
        '@stylistic/indentation': 4,
        '@stylistic/media-feature-parentheses-space-inside': 'never',
        '@stylistic/number-leading-zero': 'never',
        'at-rule-empty-line-before': [
            'always',
            {
                'except': [
                    'blockless-after-same-name-blockless',
                    'first-nested',
                ],
                'ignore': [
                    'after-comment',
                ],
                'ignoreAtRules': [
                    'extend',
                    'include',
                    'else',
                    'elseif',
                    'content',
                ],
            },
        ],
        'at-rule-no-unknown': [
            true,
            {
                'ignoreAtRules': [
                    'content',
                    'extend',
                    'include',
                    'mixin',
                    'container',
                    'if',
                    'for',
                    'forward',
                    'else',
                    'elseif',
                    'error',
                    'each',
                    'function',
                    'return',
                    'use',
                    'while',
                    'at-root',
                ],
            },
        ],
        'function-name-case': [
            'lower',
            {
                'ignoreFunctions': [
                    '/^[a-z][a-z-A-Z0-9]*$/',
                ],
            },
        ],
        'font-weight-notation': [
            'numeric',
            {
                'ignore': [
                    'relative',
                ],
            },
        ],
        'value-keyword-case': 'lower',
        'declaration-empty-line-before': [
            'always',
            {
                'except': [
                    'after-comment',
                    'after-declaration',
                    'first-nested',
                ],
            },
        ],
        'selector-attribute-quotes': 'always',
        'selector-class-pattern': '^[a-z][a-z-A-Z_0-9]*$',
        'selector-max-compound-selectors': [
            5,
            {
                'severity': 'warning',
            },
        ],
        'selector-max-id': 1,
        'selector-max-type': [
            3,
            {
                'severity': 'warning',
            },
        ],
        'selector-max-combinators': [
            5,
            {
                'severity': 'warning',
            },
        ],
        'selector-max-universal': 1,
        'selector-max-specificity': '1,3,0',
        'custom-media-pattern': '^[a-z][a-z-A-Z0-9]*$',
        'custom-property-pattern': '^[a-z][a-z-A-Z0-9]*(--[a-z0-9-]+)*$',
        'no-descending-specificity': null,
        'no-duplicate-selectors': [
            true,
            {
                'severity': 'warning',
            },
        ],
        'color-hex-length': 'short',
        'rule-empty-line-before': [
            'always',
            {
                'except': [
                    'first-nested',
                ],
                'ignore': [
                    'after-comment',
                ],
            },
        ],
        'shorthand-property-no-redundant-values': true,
        'scss/dollar-variable-pattern': '^[a-z][a-z-A-Z_0-9]*$',
        'scss/percent-placeholder-pattern': '^[a-z][a-z-A-Z0-9]*$',
        'scss/at-function-pattern': '^[a-z][a-z-A-Z0-9]*$',
        'scss/declaration-nested-properties': 'never',
        'order/order': [
            'dollar-variables',
            'custom-properties',
            'declarations',
        ],
        'order/properties-order': [
            {
                'groupName': 'var content',
                'emptyLineBefore': 'never',
                'emptyLineAfter': 'always',
                'properties': [
                    'dollar-variables',
                    'custom-properties',
                ],
            },
            {
                'groupName': 'box sizing',
                'emptyLineBefore': 'never',
                'properties': [
                    'box-sizing',
                ],
            },
            {
                'groupName': 'content / display',
                'emptyLineBefore': 'never',
                'properties': [
                    'content',
                    'counter-reset',
                    'counter-increment',
                    'counter-set',
                    'quotes',
                    'display',
                    'container',
                    'container-name',
                    'container-type',
                ],
            },
            {
                'groupName': 'buggy stuff',
                'emptyLineBefore': 'never',
                'properties': [
                    'float',
                    'clear',
                ],
            },
            {
                'groupName': 'inline alignment',
                'emptyLineBefore': 'never',
                'properties': [
                    'vertical-align',
                ],
            },
            {
                'groupName': 'overflow',
                'emptyLineBefore': 'never',
                'properties': [
                    'overflow',
                    'overflow-x',
                    'overflow-y',
                    'overflow-wrap',
                    'overflow-anchor',
                ],
            },
            {
                'groupName': 'position',
                'emptyLineBefore': 'never',
                'properties': [
                    'position',
                    'inset',
                    'inset-block',
                    'inset-block-start',
                    'inset-block-end',
                    'inset-inline',
                    'inset-inline-start',
                    'inset-inline-end',
                    'top',
                    'right',
                    'bottom',
                    'left',
                    'z-index',
                ],
            },
            {
                'groupName': 'grid',
                'emptyLineBefore': 'never',
                'properties': [
                    'grid',
                    'grid-after',
                    'grid-area',
                    'grid-auto-columns',
                    'grid-auto-flow',
                    'grid-auto-rows',
                    'grid-before',
                    'grid-column',
                    'grid-column-end',
                    'grid-column-gap',
                    'grid-column-start',
                    'grid-columns',
                    'grid-end',
                    'grid-gap',
                    'grid-row',
                    'grid-row-end',
                    'grid-row-gap',
                    'grid-row-start',
                    'grid-rows',
                    'grid-start',
                    'grid-template',
                    'grid-template-areas',
                    'grid-template-columns',
                    'grid-template-rows',
                    'gap',
                    'row-gap',
                    'column-gap',
                    'subgrid',
                ],
            },
            {
                'groupName': 'flex',
                'emptyLineBefore': 'never',
                'properties': [
                    'flex',
                    'flex-direction',
                    'flex-flow',
                    'flex-wrap',
                    'flex-grow',
                    'flex-shrink',
                    'flex-basis',
                    'justify-content',
                    'justify-items',
                    'justify-self',
                    'align-content',
                    'align-items',
                    'align-self',
                    'place-content',
                    'place-items',
                    'place-self',
                    'order',
                    'gap',
                    'row-gap',
                    'column-gap',
                ],
            },
            {
                'groupName': 'text columns',
                'emptyLineBefore': 'never',
                'properties': [
                    'columns',
                    'column-gap',
                    'column-fill',
                    'column-rule',
                    'column-rule-color',
                    'column-rule-style',
                    'column-rule-width',
                    'column-span',
                    'column-count',
                    'column-width',
                ],
            },
            {
                'groupName': 'table',
                'emptyLineBefore': 'never',
                'properties': [
                    'table-layout',
                    'empty-cells',
                    'caption-side',
                    'border-spacing',
                    'border-collapse',
                ],
            },
            {
                'groupName': 'list',
                'emptyLineBefore': 'never',
                'properties': [
                    'list-style',
                    'list-style-position',
                    'list-style-type',
                    'list-style-image',
                ],
            },
            {
                'groupName': 'box size',
                'emptyLineBefore': 'never',
                'properties': [
                    'width',
                    'height',
                    'min-width',
                    'min-height',
                    'max-width',
                    'max-height',
                    'block-size',
                    'inline-size',
                    'min-block-size',
                    'min-inline-size',
                    'max-block-size',
                    'max-inline-size',
                    'aspect-ratio',
                ],
            },
            {
                'groupName': 'box size margin',
                'emptyLineBefore': 'never',
                'properties': [
                    'margin',
                    'margin-top',
                    'margin-right',
                    'margin-bottom',
                    'margin-left',
                    'margin-block',
                    'margin-block-start',
                    'margin-block-end',
                    'margin-inline',
                    'margin-inline-start',
                    'margin-inline-end',
                ],
            },
            {
                'groupName': 'box size padding',
                'emptyLineBefore': 'never',
                'properties': [
                    'padding',
                    'padding-top',
                    'padding-right',
                    'padding-bottom',
                    'padding-left',
                    'padding-block',
                    'padding-block-start',
                    'padding-block-end',
                    'padding-inline',
                    'padding-inline-start',
                    'padding-inline-end',
                ],
            },
            {
                'groupName': 'box size border',
                'emptyLineBefore': 'never',
                'properties': [
                    'border',
                    'border-top',
                    'border-right',
                    'border-bottom',
                    'border-left',
                    'border-block',
                    'border-block-start',
                    'border-block-end',
                    'border-inline',
                    'border-inline-start',
                    'border-inline-end',
                    'border-width',
                    'border-top-width',
                    'border-right-width',
                    'border-bottom-width',
                    'border-left-width',
                    'border-block-width',
                    'border-block-start-width',
                    'border-block-end-width',
                    'border-inline-width',
                    'border-inline-start-width',
                    'border-inline-end-width',
                    'border-style',
                    'border-top-style',
                    'border-right-style',
                    'border-bottom-style',
                    'border-left-style',
                    'border-block-style',
                    'border-block-start-style',
                    'border-block-end-style',
                    'border-inline-style',
                    'border-inline-start-style',
                    'border-inline-end-style',
                    'border-radius',
                    'border-top-left-radius',
                    'border-top-right-radius',
                    'border-bottom-right-radius',
                    'border-bottom-left-radius',
                    'border-start-start-radius',
                    'border-start-end-radius',
                    'border-end-start-radius',
                    'border-end-end-radius',
                    'border-color',
                    'border-top-color',
                    'border-right-color',
                    'border-bottom-color',
                    'border-left-color',
                    'border-block-color',
                    'border-block-start-color',
                    'border-block-end-color',
                    'border-inline-color',
                    'border-inline-start-color',
                    'border-inline-end-color',
                ],
            },
            {
                'groupName': 'stroke / paint',
                'emptyLineBefore': 'never',
                'properties': [
                    'stroke-width',
                    'stroke-linecap',
                    'stroke-dasharray',
                    'stroke-dashoffset',
                    'stroke',
                    'fill',
                ],
            },
            {
                'groupName': 'font',
                'emptyLineBefore': 'never',
                'properties': [
                    'font',
                    'font-family',
                    'font-size',
                    'font-size-adjust',
                    'font-smoothing',
                    'font-stretch',
                    'font-style',
                    'font-variant',
                    'font-weight',
                    'src',
                    'line-height',
                    'letter-spacing',
                ],
            },
            {
                'groupName': 'text',
                'emptyLineBefore': 'never',
                'properties': [
                    'text-align',
                    'text-align-last',
                    'text-decoration',
                    'text-decoration-color',
                    'text-decoration-line',
                    'text-decoration-style',
                    'text-decoration-thickness',
                    'text-underline-offset',
                    'text-indent',
                    'text-justify',
                    'text-overflow',
                    'text-overflow-ellipsis',
                    'text-overflow-mode',
                    'text-rendering',
                    'text-outline',
                    'text-shadow',
                    'text-transform',
                    'text-wrap',
                    'text-wrap-mode',
                    'text-wrap-style',
                    'word-wrap',
                    'word-break',
                    'white-space',
                    'white-space-collapse',
                    'word-spacing',
                    'hyphens',
                    'hyphenate-character',
                    'text-emphasis',
                    'text-emphasis-color',
                    'text-emphasis-style',
                    'text-emphasis-position',
                ],
            },
            {
                'groupName': 'coloring / background',
                'emptyLineBefore': 'never',
                'properties': [
                    'color',
                    'background',
                    'background-attachment',
                    'background-clip',
                    'background-color',
                    'background-image',
                    'background-repeat',
                    'background-position',
                    'background-size',
                ],
            },
            {
                'groupName': 'outline',
                'emptyLineBefore': 'never',
                'properties': [
                    'outline',
                    'outline-color',
                    'outline-offset',
                    'outline-style',
                    'outline-width',
                ],
            },
            {
                'groupName': 'visual / non layout',
                'emptyLineBefore': 'never',
                'properties': [
                    'box-shadow',
                    'visibility',
                    'opacity',
                    'filter',
                    'backdrop-filter',
                    'mix-blend-mode',
                    'isolation',
                    'transform',
                    'transform-box',
                    'transform-origin',
                    'transform-style',
                    'backface-visibility',
                    'perspective',
                    'perspective-origin',
                ],
            },
            {
                'groupName': 'transform and animation',
                'emptyLineBefore': 'never',
                'properties': [
                    'transition',
                    'transition-property',
                    'transition-duration',
                    'transition-timing-function',
                    'transition-delay',
                    'transition-behavior',
                    'animation',
                    'animation-name',
                    'animation-duration',
                    'animation-play-state',
                    'animation-timing-function',
                    'animation-delay',
                    'animation-iteration-count',
                    'animation-direction',
                    'animation-fill-mode',
                    'animation-composition',
                    'animation-timeline',
                    'animation-range',
                    'animation-range-start',
                    'animation-range-end',
                    'view-transition-name',
                    'view-transition-class',
                ],
            },
            {
                'groupName': 'aria, other and obscure',
                'emptyLineBefore': 'never',
                'properties': [
                    'appearance',
                    'content-visibility',
                    'contain',
                    'contain-intrinsic-size',
                    'contain-intrinsic-width',
                    'contain-intrinsic-height',
                    'contain-intrinsic-block-size',
                    'contain-intrinsic-inline-size',
                    'will-change',
                    'scroll-behavior',
                    'scroll-snap-type',
                    'scroll-snap-align',
                    'scroll-snap-stop',
                    'scroll-margin',
                    'scroll-margin-top',
                    'scroll-margin-right',
                    'scroll-margin-bottom',
                    'scroll-margin-left',
                    'scroll-margin-block',
                    'scroll-margin-block-start',
                    'scroll-margin-block-end',
                    'scroll-margin-inline',
                    'scroll-margin-inline-start',
                    'scroll-margin-inline-end',
                    'scroll-padding',
                    'scroll-padding-top',
                    'scroll-padding-right',
                    'scroll-padding-bottom',
                    'scroll-padding-left',
                    'scroll-padding-block',
                    'scroll-padding-block-start',
                    'scroll-padding-block-end',
                    'scroll-padding-inline',
                    'scroll-padding-inline-start',
                    'scroll-padding-inline-end',
                    'scroll-timeline',
                    'scroll-timeline-name',
                    'scroll-timeline-axis',
                    'overscroll-behavior',
                    'overscroll-behavior-x',
                    'overscroll-behavior-y',
                    'overscroll-behavior-block',
                    'overscroll-behavior-inline',
                    'anchor-name',
                    'anchor-scope',
                    'position-anchor',
                    'position-area',
                    'position-try',
                    'position-try-options',
                    'position-try-fallbacks',
                    'position-visibility',
                    'tab-size',
                    'resize',
                    'cursor',
                    'caret-color',
                    'accent-color',
                    'pointer-events',
                    'touch-action',
                    'speak',
                    'user-select',
                    'nav-index',
                    'nav-up',
                    'nav-right',
                    'nav-down',
                    'nav-left',
                    'clip',
                    'clip-path',
                    'zoom',
                ],
            },
        ],
    },
};
